font:
  size: 16 # 16,20,28,36
  family: 1 # 1,2,3
services:
  background_color: "#b2f2bb"
  fill: "hachure" # "hachure","cross-hatch", "solid"
ports:
  background_color: "#a5d8ff"
  fill: "hachure" # "hachure","cross-hatch", "solid"
