name: Release 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feat/docker-image-revisiting
    paths:
      - src/**
      - Cargo.toml

env:
  RUST_TOOLCHAIN: nightly-2023-05-03
  BUILD_VERSION_PREFIX: v0.1.6
  CARGO_PROFILE: release

permissions:
  contents: write

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Show cargo version
        run: cargo --version
      - name: Install cross
        run: |
          cargo install cross --git https://github.com/cross-rs/cross
      - name: Fetch
        run: |
          cargo fetch
      - name: Build x86_64-unknown-linux-musl
        run: |
          cargo clean && cross build --target=x86_64-unknown-linux-musl --release
      - name: Package x86_64-unknown-linux-musl
        run: |
            ls -lah
            mkdir -p excalidocker-x86_64-linux &&
            mv target/x86_64-unknown-linux-musl/release/excalidocker excalidocker-x86_64-linux
      - name: Build aarch64-unknown-linux-musl
        run: |
          cargo clean && cross build --target=aarch64-unknown-linux-musl --release
      - name: Package aarch64-unknown-linux-musl
        run: |
          mkdir -p excalidocker-aarch64-linux &&
          mv target/aarch64-unknown-linux-musl/release/excalidocker excalidocker-aarch64-linux        
